{% set version = "1.18" %}

package:
  name: r-aqp
  version: {{ version|replace("-", "_") }}

source:
  fn: aqp_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/aqp_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/aqp/aqp_{{ version }}.tar.gz
  sha256: 2352625aadffd1496ee737b14edd333595b0fc4a9c4961f37204372e3ebfa164

build:
  noarch: generic
  number: 0
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-hmisc
    - r-mass
    - r-rcolorbrewer
    - r-cluster
    - r-digest
    - r-lattice
    - r-plotrix
    - r-plyr
    - r-reshape
    - r-scales
    - r-sp
    - r-stringr
  run:
    - r-base
    - r-hmisc
    - r-mass
    - r-rcolorbrewer
    - r-cluster
    - r-digest
    - r-lattice
    - r-plotrix
    - r-plyr
    - r-reshape
    - r-scales
    - r-sp
    - r-stringr

test:
  commands:
    - $R -e "library('aqp')"  # [not win]
    - "\"%R%\" -e \"library('aqp')\""  # [win]

about:
  home: https://github.com/ncss-tech/aqp
  license: GPL (>= 3)
  summary: A collection of algorithms related to modeling of soil resources, soil classification,
    soil profile aggregation, and visualization.
  license_family: GPL3

extra:
  recipe-maintainers:
    - ocefpaf
