{% set version = "1.42" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-aqp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/aqp_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/aqp/aqp_{{ version }}.tar.gz
  sha256: d40d4ae964516cc94876a90a24c545a2f11826a57b77accb9bb8e02970cfaf1a

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cluster
    - r-data.table
    - r-lattice
    - r-plyr
    - r-sp
    - r-stringr
  run:
    - r-base
    - r-cluster
    - r-data.table
    - r-lattice
    - r-plyr
    - r-sp
    - r-stringr

test:
  commands:
    - $R -e "library('aqp')"           # [not win]
    - "\"%R%\" -e \"library('aqp')\""  # [win]

about:
  home: https://github.com/ncss-tech/aqp
  license: GPL-3.0-or-later
  summary: The Algorithms for Quantitative Pedology (AQP) project was started in 2009 to organize a loosely-related set of concepts and source code on the topic of soil profile visualization, aggregation, and classification into this package (aqp). Over the past 8 years, the project has grown into a suite of related R packages
    that enhance and simplify the quantitative analysis of soil profile data. Central to the AQP project is a new vocabulary of specialized functions and data structures that can accommodate the inherent complexity of soil profile information; freeing the scientist to focus on ideas rather than boilerplate data processing
    tasks <doi:10.1016/j.cageo.2012.10.020>. These functions and data structures have been extensively tested and documented, applied to projects involving hundreds of thousands of soil profiles, and deeply integrated into widely used tools such as SoilWeb <https://casoilresource.lawr.ucdavis.edu/soilweb-apps/>. Components
    of the AQP project (aqp, soilDB, sharpshootR, soilReports packages) serve an important role in routine data analysis within the USDA-NRCS Soil Science Division. The AQP suite of R packages offer a convenient platform for bridging the gap between pedometric theory and practice.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: aqp
# Version: 1.25
# Date: 2020-10-15
# Title: Algorithms for Quantitative Pedology
# Authors@R: c(person(given="Dylan", family="Beaudette", role = c("aut", "cre"), email = "dylan.beaudette@usda.gov"), person(given="Pierre", family="Roudier", email="roudierp@landcareresearch.co.nz", role = c("aut", "ctb")), person(given="Andrew", family="Brown", email="andrew.g.brown@usda.gov", role = c("aut", "ctb")))
# Author: Dylan Beaudette [aut, cre], Pierre Roudier [aut, ctb], Andrew Brown [aut, ctb]
# Maintainer: Dylan Beaudette <dylan.beaudette@usda.gov>
# Depends: R (>= 3.5.0)
# Imports: grDevices, graphics, stats, utils, methods, plyr, reshape, grid, lattice, cluster, sp, stringr
# Suggests: colorspace, maptools, foreign, ape, soilDB, latticeExtra, maps, compositions, sharpshootR, markovchain, xtable, testthat, Gmedian, farver, Hmisc, rlang, data.table, tibble, RColorBrewer, scales, digest, MASS, mpspline2, soiltexture
# Description: The Algorithms for Quantitative Pedology (AQP) project was started in 2009 to organize a loosely-related set of concepts and source code on the topic of soil profile visualization, aggregation, and classification into this package (aqp). Over the past 8 years, the project has grown into a suite of related R packages that enhance and simplify the quantitative analysis of soil profile data. Central to the AQP project is a new vocabulary of specialized functions and data structures that can accommodate the inherent complexity of soil profile information; freeing the scientist to focus on ideas rather than boilerplate data processing tasks <doi:10.1016/j.cageo.2012.10.020>. These functions and data structures have been extensively tested and documented, applied to projects involving hundreds of thousands of soil profiles, and deeply integrated into widely used tools such as SoilWeb <https://casoilresource.lawr.ucdavis.edu/soilweb-apps/>. Components of the AQP project (aqp, soilDB, sharpshootR, soilReports packages) serve an important role in routine data analysis within the USDA-NRCS Soil Science Division. The AQP suite of R packages offer a convenient platform for bridging the gap between pedometric theory and practice.
# License: GPL (>= 3)
# LazyLoad: yes
# Repository: CRAN
# URL: https://github.com/ncss-tech/aqp
# BugReports: https://github.com/ncss-tech/aqp/issues
# Encoding: UTF-8
# RoxygenNote: 7.1.1
# NeedsCompilation: no
# Packaged: 2020-10-19 16:28:31 UTC; Dylan.Beaudette
# Date/Publication: 2020-10-19 22:10:06 UTC
