appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: nJdtlnv2bWfhsoq5oUizwbfnwHFvrRcdG8qn4hkCQp5vChHQmH8fKIDFBwY5JSd+7W0cTrBaS0NKH52LyYNWT1z7Hn8SMaulp9gROmO8DjiQWiNWh2uJX4GO+Wtofy5YfNeYxpT3zbGgJI31vxnv+fQnZZZHYoWjPKAD7bJSUADapmxPN6MkUGDdSBDULYYGZDeGcDGXBUFUu+qsLSmfFAIWB0DdNZIh/q2xVla+lWMv2LHCJB/P3TbVaXgH+iIUd/p8NktDJ1qXzfFb7i+E2YTxVzRnwdNgwsJTPPVrQuW9NnUYhM7dbdgsOLWn0e5uWOhJCMxb1ttyisTq9r11AQRlVENQPq6kmUyFzmx/d0jYSfn03zMvjKYZwZ/wuhyZnZOLvHaJc/FAoZsjDRqVNnLJKKCq683E/gbD9KXWzpNDziC63h2xfEQaOE0ZrSuKnnV3pGArhzdpEv8N5DxQ19ESc+DK08BKE/yHTm9hDMolVRxjDm9Uevc8mpceC4qz4MxfCnwi4pAra5uybm//4kXceqTPFW4NQYinvZO5Ea75hHIoBsDoKZK0vtGgq9eYAxFjUcliTeypF2bWP5ZqBvaUn22/hYBrst3wvl2/Fdny1s3SmeVksE6ytD4OF0FiSYFZ7xsoPXHwVxgQy041SNTenAoYzN47xOndy0Ne+zI=}
